#!/bin/bash
echo "Select Your word Number"
curl http://semes-olla.rhcloud.com/words?Swadesh/English.py

read -p 'Enter nubmer of your word to Translate' INPUT 
echo $INPUT
url="http://semes-olla.rhcloud.com/word?$INPUT&Swadesh/Hindi.py"
echo $url
curl $url
